# Efrain's personal rubocop setup... 
#
# This file only contains rules that differ from the rubocop defaults.
#

# Style

Style/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false 

Style/Encoding:
  EnforcedStyle: when_needed
  SupportedStyles:
    - when_needed
    - always

Style/IfUnlessModifier:
  Enabled: false

Style/Next:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist: []

Style/SignalException:
  EnforcedStyle: only_raise
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space
  SupportedStyles:
    - space
    - no_space

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to ~120 characters.'
  Max: 125
  AllowURI: true

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Lint
Lint/Debugger:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
